# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389af88d248040e29cba0a501545296c49190c74ee4ea78f690381682e7c88e3cafc99b48e5f87b56285e0b20a7be888119dece9d90686dadd7e28c881785a0a

test:
  secret_key_base: 31cedc5c5570e86bb9cf252a66afc4e0280228b16229a8ce09c015f516bb86cc714bf495fb44f15d7ad618e08a3280adea47619efa5cd569a4958455de4e52c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
